version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iconduct-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/config:/app/config
      - ./backend/logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - AWS_REGION=eu-central-1
      - S3_BUCKET=shayg-test-grafana
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    restart: unless-stopped
    networks:
      - iconduct-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: iconduct-frontend
    ports:
      - "3333:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: unless-stopped
    networks:
      - iconduct-network

networks:
  iconduct-network:
    driver: bridge